global:
  target_col: Churn

paths:
  raw_train_path: data/raw/raw_train.csv
  raw_test_path: data/raw/raw_test.csv

  interim_train_path: "data/interim/X_train.csv"
  interim_test_path: "data/interim/X_test.csv"

  interim_y_train_path: "data/interim/y_train.csv"
  interim_y_test_path: "data/interim/y_test.csv"

  dropped_features_path: data/dropped_features.pkl


  model_pipeline_path: data/model/model_pipeline.pkl


data_ingestion:
  train_db_name: churn_train
  test_db_name: churn_test
  binary_cols_to_map:
    - International plan
    - Voice mail plan
 
feature_engineering:
  corr_threshold: 0.70

  
model_training:
  params:
    max_depth: 5
    learning_rate: 0.010186656321288096
    n_estimators: 574
    subsample: 0.6434239171890623
    colsample_bytree: 0.7317375561686101
    reg_alpha: 6.92738333659976
    scale_pos_weight: 5.966855473903635
    random_state: 42
    eval_metric: logloss
  mlflow:
    experiment_name: "ml_project"
    model_name: "xgb_classifier"