paths:
  raw_train_path: data/raw/raw_train.csv
  raw_test_path: data/raw/raw_test.csv

  interim_train_path: "data/interim/X_train.csv"
  interim_test_path: "data/interim/X_test.csv"

  interim_y_train_path: "data/interim/y_train.csv"
  interim_y_test_path: "data/interim/y_test.csv"

  dropped_features_path: data/dropped_features.pkl


data_ingestion:
  train_db_name: churn_train
  test_db_name: churn_test
  target_col: Churn
  binary_cols_to_map:
    - International plan
    - Voice mail plan
 
data_transformation:

  target_col: "Churn"
  corr_threshold: 0.70
